---
apiVersion: v1
kind: Pod
metadata:
  name: utilities
spec:
  containers:
  - name: utilities 
    image: sudermanjr/utilities:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
