apiVersion: apps/v1
kind: Deployment
metadata:
  name: utilities
  labels:
    app: utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utilities
  template:
    metadata:
      labels:
        app: utilities
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: utilities
        image: sudermanjr/utilities:latest
        # Just spin & wait forever
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
