version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
          docker build -t sudermanjr/utilities:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sudermanjr/utilities:$TAG
