version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              bash
      - run:
          name: Build application Docker image
          command: |
            docker build -t sudermanjr/utilities:build .
      - run:
          name: Run tests
          command: |
            ./run_tests.sh sudermanjr/utilities:build
      - store_artifacts:
          path: test-results
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG="sudermanjr/utilities:latest"
            else
              TAG="sudermanjr/utilities:1.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}"
            fi
            echo "Pushing docker image: '$TAG'"
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
            docker tag sudermanjr/utilities:build $TAG
            docker push $TAG
